#!/bin/bash

sudo echo "Copying config files..."

cp .asoundrc .xinitrc .zshrc .zcompdump $HOME/
cp -r aliases dwm wallpaper $HOME/.config/

echo "Install dwm config now?"
read prompt1

if [ -z "$prompt1" ] || [ $prompt1 = "y" ]; then
    echo "Installing dwm..."
    
    cd $HOME/.config/dwm/
    sudo make install clean

    echo "Installing dwm config successful. Please restart dwm."
    return
fi

echo "Exiting install prompt..."
