#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# 240422 - archaei: adding shutdown and reboot option to grub
submenu "Turn off or Reboot" {
	menuentry "Turn off the Computer" {
		echo "Shutting Down..."
		halt
	}
	menuentry "Reboot" {
		echo "Rebooting system..."
		reboot
	}
}
