#!/bin/bash

# archaei : Starting Music through dmenu using MPV 
# dmenu, mpv, base_devel

musicDirectory="$HOME/Music/"
opt="$(echo -e 'Playlists\nFiles\nQuit' | dmenu -p 'mpvMusic' -c -l 5)"
mpvDir () { 
  mpvCommand="$(find "$2" -type $1 | dmenu -p "Music Directory :" -c -l 5 -i)"
}

case $opt in
  "Playlists")
    mpvDir "d" "$musicDirectory"
    ;;
  "Files")
    mpvDir "d" "$musicDirectory"
    mpvDir "f" "$mpvCommand"
    ;;
esac

[[ -n $mpvCommand ]] && mpv "$mpvCommand" || exit 0
